ALTER TABLE artists AUTO_INCREMENT = 1;
ALTER TABLE concerts AUTO_INCREMENT = 1;
ALTER TABLE locations AUTO_INCREMENT = 1;
ALTER TABLE roles AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE tickets AUTO_INCREMENT = 1;