package networking;

public enum RequestType {
    UPDATES,LOGIN,ADD, GET_CONCERTS, GET_LOCATIONS, GET_CONCERTS_BY_ARTIST, GET_CONCERTS_BY_DATE, GET_CONCERTS_BY_ARTIST_AND_DATE, SAVE_TICKET, UPDATE_CONCERT, GET_ARTISTS
}
